services:
  postgres:
    image: postgres:16
    container_name: postgres
    environment:
      POSTGRES_DB: bookstore
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./docker-volume/book-store-db:/var/lib/postgresql/data

volumes:
  postgres_data: